### PR TITLE
fix(select): supply keymap mode

### LINKED ISSUE #270: Keymap issues after fix for #232
**Describe the bug**

Two keymap issues after that commit is applied:

1. Visual maps no longer work (for example, can change around functions with `caf`, but can no longer select the function with `vaf`)
2. Running `doautocmd FileType <ft>` triggers "No such mapping" (just like in #169)

**To Reproduce**

Try to execute a visual mapping.

**Expected behavior**

Object is seleted.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - rust           ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - todotxt        ✓ . . . .
  - ql             ✓ ✓ . ✓ ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - scheme         ✓ . ✓ . ✓
  - bibtex         ✓ . ✓ ✓ .
  - kotlin         ✓ ✓ ✓ . ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - gitignore      ✓ . . . .
  - yang           ✓ . ✓ ✓ .
  - scss           ✓ . . ✓ .
  - zig            ✓ . ✓ ✓ ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - pioasm         ✓ . . . ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - rego           ✓ . . . ✓
  - tiger          ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓
  - fusion         ✓ ✓ ✓ ✓ .
  - php            ✓ ✓ ✓ ✓ ✓
  - tlaplus        ✓ ✓ ✓ . ✓
  - m68k           ✓ ✓ ✓ . ✓
  - proto          ✓ . ✓ . .
  - http           ✓ . . . ✓
  - rnoweb         ✓ . ✓ . ✓
  - teal           ✓ ✓ ✓ ✓ ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - elm            ✓ . . . ✓
  - regex          ✓ . . . .
  - query          ✓ ✓ ✓ ✓ ✓
  - cmake          ✓ . ✓ . .
  - rasi           ✓ ✓ ✓ ✓ .
  - hjson          ✓ ✓ ✓ ✓ ✓
  - vala           ✓ . ✓ . .
  - gdscript       ✓ ✓ . ✓ ✓
  - norg           . . . . .
  - hack           ✓ . . . .
  - foam           ✓ ✓ ✓ ✓ ✓
  - sql            ✓ . . . ✓
  - solidity       ✓ . . . .
  - graphql        ✓ . . ✓ ✓
  - ninja          ✓ . ✓ ✓ .
  - devicetree     ✓ ✓ ✓ ✓ ✓
  - llvm           ✓ . . . .
  - hocon          ✓ . . . ✓
  - lalrpop        ✓ ✓ . . .
  - json5          ✓ . . . ✓
  - help           ✓ . . . .
  - meson          ✓ . ✓ . ✓
  - vim            ✓ ✓ ✓ . ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - cooklang       ✓ . . . .
  - commonlisp     ✓ ✓ ✓ . .
  - c              ✓ ✓ ✓ ✓ ✓
  - haskell        ✓ . ✓ . ✓
  - fortran        ✓ . ✓ ✓ .
  - latex          ✓ . ✓ . ✓
  - clojure        ✓ ✓ ✓ . ✓
  - wgsl           ✓ . ✓ . .
  - sparql         ✓ ✓ ✓ ✓ ✓
  - agda           ✓ . ✓ . .
  - hlsl           ✓ ✓ ✓ ✓ ✓
  - r              ✓ ✓ . ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - prisma         ✓ . . . .
  - toml           ✓ ✓ ✓ ✓ ✓
  - scala          ✓ . ✓ . ✓
  - qmljs          ✓ . ✓ . .
  - slint          ✓ . . ✓ .
  - json           ✓ ✓ ✓ ✓ .
  - java           ✓ ✓ . ✓ ✓
  - racket         ✓ . ✓ . ✓
  - beancount      ✓ . ✓ . .
  - jsdoc          ✓ . . . .
  - css            ✓ . ✓ ✓ ✓
  - fennel         ✓ ✓ . . ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - comment        ✓ . . . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - embedded_template✓ . . . ✓
  - swift          ✓ ✓ . . .
  - pascal         ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - verilog        ✓ ✓ ✓ . ✓
  - gomod          ✓ . . . ✓
  - dot            ✓ . . . ✓
  - astro          ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - dart           ✓ ✓ . ✓ ✓
  - d              ✓ . ✓ ✓ ✓
  - org            . . . . .
  - python         ✓ ✓ ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - make           ✓ . . . ✓
  - elvish         ✓ . . . ✓
  - gowork         ✓ . . . ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - vue            ✓ . ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - v              ✓ ✓ ✓ ✓ ✓
  - elixir         ✓ ✓ ✓ ✓ ✓
  - eex            ✓ . . . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - erlang         ✓ . ✓ . .
  - rst            ✓ ✓ . . ✓
  - godot_resource ✓ ✓ ✓ . .
  - cpp            ✓ ✓ ✓ ✓ ✓
  - ledger         ✓ . ✓ ✓ ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - turtle         ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - ocamllex       ✓ . . . ✓
  - perl           ✓ . ✓ . .
  - hcl            ✓ . ✓ ✓ ✓
  - pug            ✓ . . . ✓
  - fish           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.8.0-dev-1005-g6484c5687
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/fsouza/Projects/os/3/neovim/build/cmake.config -I/Users/fsouza/Projects/os/3/neovim/src -I/Users/fsouza/Projects/os/3/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/Users/fsouza/Projects/os/3/neovim/build/src/nvim/auto -I/Users/fsouza/Projects/os/3/neovim/build/include
Compiled by fsouza@xikinbookpro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/fsouza/opt/neovim/share/nvim"

Run :checkhealth for more info
```

**Additional context**

Pinning nvim-treesitter-textobjects to https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/775c5dbcb6937954d5861465e7c3ec23b855af93 "fixes" the issue for me.

### PR DESCRIPTION
**Pull request by AckslD**
Seems the keymap mode got lost after #232 

Closes #270

### CODE REVIEW

File: lua/nvim-treesitter/textobjects/select.lua [hunk 1]
```diff
@@ -152,9 +152,11 @@ function M.attach(bufnr, lang)
...
     if query then
-      vim.keymap.set({ "o", "x" }, mapping, function()
-        require("nvim-treesitter.textobjects.select").select_textobject(query)
-      end, { buffer = buf, silent = true, remap = false, desc = desc })
+      for _, mode in ipairs { "o", "x" } do
+        vim.keymap.set(mode, mapping, function()
+          require("nvim-treesitter.textobjects.select").select_textobject(query, mode)
+        end, { buffer = buf, silent = true, remap = false, desc = desc })
+      end
     end
```
Comment (fsouza) [inline lua/nvim-treesitter/textobjects/select.lua:160]: Theseines are equivalent: vim.keymap.set can take the modes as a table.

The mapping exists, but it doesn't do what it used to. If I'm not mistaken, using a callback with vim.keymap.set in visual mode requires taking some steps in the callback, meaning the same callback can't really be used (unless it inspects the parameters to check the mode).

Comment (AckslD) [reply lua/nvim-treesitter/textobjects/select.lua:160]: Hmm maybe there are more issues with this but at least the `mode` is now passed to `select_textobject` as it was before the change to `vim.keymap.set`.

Comment (theHamsta) [reply lua/nvim-treesitter/textobjects/select.lua:160]: So we should just go back to what it was before?

Comment (fsouza) [reply lua/nvim-treesitter/textobjects/select.lua:160]: > Hmm maybe there are more issues with this but at least the `mode` is now passed to `select_textobject` as it was before the change to `vim.keymap.set`.

Oh interesting, I wonder if there's a bug in neovim upstream when passing multiple modes to vim.keymap.set? 🤔

**Review by theHamsta — APPROVED** [review]
