### PR TITLE
mapcheck before keymap.del

### LINKED ISSUE #362: Error "E31: No such mapping" in file `select.lua` when trying to call `vim.keymap.del`
# Describe the bug
When the content of a buffer is changed by [telescope](https://github.com/nvim-telescope/telescope.nvim)'s builtin action `git_bcommits`, nvim-treesitter-textobjects throws the error:

```
E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:78
5: Vim(append):Error executing lua callback: vim/keymap.lua:0: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        vim/keymap.lua: in function 'del'
        ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:206: in function 'det
ach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:518: in function 'det
ach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:527: in function 'rea
ttach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...
er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
        [C]: in function 'cmd'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:785: in function 'run
_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_
replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_
func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:352: in function 'exe
cute_keymap'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'cmd'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:785: in function 'run
_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_
replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_
func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:352: in function 'exe
cute_keymap'
        [string ":lua"]:1: in main chunk
```

# To Reproduce

Assume using [packer.nvim](https://github.com/wbthomason/packer.nvim) as the plugin manager.

1. Clone [packer.nvim](https://github.com/wbthomason/packer.nvim) to `~/.local/share/nvim/site/pack/packer/start`
2. Use the following minimal config:

    ```lua
    vim.cmd('packadd packer.nvim')
    require('packer').startup(function(use)
        use('wbthomason/packer.nvim')

        use({
            'nvim-treesitter/nvim-treesitter',
            config = function()
                local ts_configs = require('nvim-treesitter.configs')
                ts_configs.setup({
                    ensure_installed = require('utils.static').langs:list('ts'),
                    sync_install = true,
                    ignore_install = {},
                    highlight = {
                        enable = true,
                        additional_vim_regex_highlighting = false,
                    },
                    context_commentstring = {
                        enable = true,
                    },
                    textobjects = {
                        select = {
                            enable = true,
                            lookahead = true, -- Automatically jump forward to textobj
                            keymaps = {
                                -- You can use the capture groups defined in textobjects.scm
                                ['am'] = '@function.outer',
                                ['im'] = '@function.inner',
                                ['al'] = '@loop.outer',
                                ['il'] = '@loop.inner',
                                ['ak'] = '@class.outer',
                                ['ik'] = '@class.inner',
                                ['aa'] = '@parameter.outer',
                                ['ia'] = '@parameter.inner',
                                ['a/'] = '@comment.outer',
                                ['i/'] = '@comment.inner',
                                ['a*'] = '@comment.outer',
                                ['i*'] = '@comment.inner',
                            },
                        },
                        move = {
                            enable = true,
                            set_jumps = true, -- whether to set jumps in the jumplist
                            goto_next_start = {
                                [']m'] = '@function.outer',
                                [']]'] = '@function.outer',
                                [']k'] = '@class.outer',
                                [']}'] = '@class.outer',
                                [']a'] = '@parameter.outer'
                            },
                            goto_next_end = {
                                [']M'] = '@function.outer',
                                [']['] = '@function.outer',
                                [']K'] = '@class.outer',
                                [']{'] = '@class.outer',
                                [']A'] = '@parameter.outer'
                            },
                            goto_previous_start = {
                                ['[m'] = '@function.outer',
                                ['[['] = '@function.outer',
                                ['[k'] = '@class.outer',
                                ['[{'] = '@class.outer',
                                ['[a'] = '@parameter.outer'
                            },
                            goto_previous_end = {
                                ['[M'] = '@function.outer',
                                ['[]'] = '@function.outer',
                                ['[K'] = '@class.outer',
                                ['[}'] = '@class.outer',
                                ['[A'] = '@parameter.outer'
                            },
                        },
                        swap = {
                            enable = true,
                            swap_next = {
                                ['<C-l>'] = '@parameter.inner'
                            },
                            swap_previous = {
                                ['<C-h>'] = '@parameter.inner'
                            },
                        },
                        lsp_interop = {
                            enable = true,
                            border = 'single',
                            peek_definition_code = {
                                ['<leader>p'] = '@function.outer',
                            },
                        },
                    },
                })
            end,
        })

        use({
            'nvim-treesitter/nvim-treesitter-textobjects',
            requires = 'nvim-treesitter',
            after = 'nvim-treesitter',
        })

        use({
            'nvim-telescope/telescope.nvim',
            requires = 'nvim-lua/plenary.nvim',
            config = function()
                local telescope = require('telescope')
                telescope.setup()
            end,
        })
    end)
    ```

    save it as `~/.config/init_test.lua`

4. Run `nvim -u ~/.config/init_test.lua`.
5. Inside neovim, open an arbitrary file tracked by git inside a local git repository.
6. Inside neovim, run command `:Telescope git_bcommits`
7. Select a random commit, press `<Enter>`
8. See the error

# Expected behavior

should not error.

# Output of `:checkhealth nvim-treesitter`

```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.4.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.6-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 14 Jan 2023 13:09:35 +0000"
} ~

Parser/Features         H L F I J
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

# Output of `nvim --version`

I'm currently on Neovim nightly, but this bug is consistent on stable version:

```
NVIM v0.9.0-dev-672+g4876654d4c
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by zeng

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

# Additional context

The bug is cause by `lua/nvim-treesitter/textobjects/select.lua`, line 206, where we try to delete a buffer keymap:

```lua
205    if query then
206      vim.keymap.del({ "o", "x" }, mapping, { buffer = bufnr })
207    end
```

for some reason, this mapping does not exist, so the error is thrown.

Change line 206 to

```lua
vim.cmd(string.format('silent!' .. 'lua vim.keymap.del({ "o", "x" }, %s, { buffer = %s })', mapping, bufnr))
```

solves the issue, however I belive this is just a temporary fix, there must be something wrong elsewhere.

A short video clip demonstrating this bug:

https://user-images.githubusercontent.com/76579810/212854314-f93e3052-0533-4da6-9cca-632def8a6c0b.mp4

### PR DESCRIPTION
**Pull request by kiyoon**
Resolves #362

### CODE REVIEW

File: lua/nvim-treesitter/textobjects/select.lua [hunk 1]
```diff
@@ -203,7 +203,11 @@ function M.detach(bufnr)
       query = query.query
     end
     if query then
-      vim.keymap.del({ "o", "x" }, mapping, { buffer = bufnr })
+      for _, mode in ipairs { "o", "x" } do
+        if vim.fn.mapcheck(mapping, mode, false) ~= "" then
+          vim.keymap.del(mode, mapping, { buffer = bufnr })
+        end
+      end
```
Comment (theHamsta) [inline lua/nvim-treesitter/textobjects/select.lua:210]: any idea why this happens? the checks to set the mappings and to unset them are symmetric. Unless something changed in the meantime (e.g. config change) this shouldn't cause a problem.

But still better to check before the unset 👍

**Review by theHamsta — APPROVED** [review]

File: lua/nvim-treesitter/textobjects/select.lua (hunk 1 above)
Comment (kiyoon) [reply lua/nvim-treesitter/textobjects/select.lua:210]: I actually couldn't reproduce it in my settings, but maybe when the setup has the wrong keymap (like `a*` or `a/`. I don't know if they are allowed) it isn't set at all to begin with? Also I noticed that the setting contains non-existing queries
